export const PRODOCT_LIST_REQUEST='PRODOCT_LIST_REQUEST';
export const PRODOCT_LIST_SUCCESS='PRODOCT_LIST_SUCCESS';
export const PRODOCT_LIST_FAIL='PRODOCT_LIST_FAIL';

export const PRODOCT_DETAILS_REQUEST='PRODOCT_DETAILS_REQUEST';
export const PRODOCT_DETAILS_SUCCESS='PRODOCT_DETAILS_SUCCESS';
export const PRODOCT_DETAILS_FAIL='PRODOCT_DETAILS_FAIL';