export const PRODOCT_LIST_REQUEST='PRODOCT_LIST_REQUEST';
export const PRODOCT_LIST_SUCCESS='PRODOCT_LIST_SUCCESS';
export const PRODOCT_LIST_FAIL='PRODOCT_LIST_FAIL';
export const PRODOCT_LIST_RESET = "PRODOCT_LIST_RESET"

export const PRODOCT_DETAILS_REQUEST='PRODOCT_DETAILS_REQUEST';
export const PRODOCT_DETAILS_SUCCESS='PRODOCT_DETAILS_SUCCESS';
export const PRODOCT_DETAILS_FAIL='PRODOCT_DETAILS_FAIL';
export const PRODOCT_DETAILS_RESET = "PRODOCT_DETAILS_RESET"

export const PRODOCT_DELETE_REQUEST='PRODOCT_DELETE_REQUEST';
export const PRODOCT_DELETE_SUCCESS='PRODOCT_DELETE_SUCCESS';
export const PRODOCT_DELETE_FAIL='PRODOCT_DELETE_FAIL';

export const PRODOCT_CREATE_REQUEST='PRODOCT_CREATE_REQUEST';
export const PRODOCT_CREATE_SUCCESS='PRODOCT_CREATE_SUCCESS';
export const PRODOCT_CREATE_FAIL='PRODOCT_CREATE_FAIL';
export const PRODOCT_CREATE_RESET='PRODOCT_CREATE_RESET';
